# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Bulma Blog"
license = "MIT"
licenselink = "https://github.com/ShawnOY/hugo-bulma-blog/blob/master/LICENSE"
description = "TBD"
homepage = "https://github.com/ShawnOY/hugo-bulma-blog"
tags = ["blog", "bulma"]
features = ["blog"]
min_version = "0.55.0"

[author]
  name = "Shawn OY"
  homepage = "https://blog.0x427567.com/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
